name: Nightly build Ubuntu

on: [push]

jobs:
  compile_pak192-comic:

    runs-on: ubuntu-latest
   
    steps:
    - uses: actions/checkout@v1

    - name: install_dependencies
      run: |
        sudo apt-get -y update
        sudo apt-get -ym install libpng-dev
        sudo apt-get -ym install libsdl2-dev
        sudo apt-get -ym install libbz2-dev
        sudo apt-get -ym install autoconf
        git clone https://github.com/jamespetts/simutrans-extended.git simutrans-extended
    - name: setup
      run: |
        cd simutrans-extended
        autoconf
        ./configure
        cat config.default >>/dev/stderr
    - name: make makeobj
      run: |
          cd simutrans-extended/makeobj
          make
          mv makeobj-extended ../../..
          cd ../../..
          rm -rf simutrans
    - name: make pak192
      run: |
        bash COMPILE.sh
    - name: Rename result
      run: |
        mv compiled pak192.comic-nightly
        zip -r pak192-nightly.zip pak192.comic-nightly
    - name: Update binaries of Nightly Release
      uses: svenstaro/upload-release-action@v1-release
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ./pak192-nightly.zip
        asset_name: pak192-nightly.zip
        tag: Nightly
        overwrite: true
